//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptecaAlexandrova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        public int Id { get; set; }
        public int MedicinesId { get; set; }
        public Nullable<int> Operation_number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Sum { get; set; }
        public string Status { get; set; }
    
        public virtual Medicine Medicine { get; set; }
    }
}
